name: Run training logic
on:
  schedule:
    - cron: '13 10 * * *'
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  trainer:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: { python-version: '3.9' }
      - name: Install cbng-trainer
        run: pip install git+https://github.com/cluebotng/trainer.git@main
      - name: Download reviewed edits
        run: cbng-trainer download-edits --output=edits.xml
      - name: Build databases
        run: |
          mkdir -p new
          cbng-trainer build-database --input=edits.xml --output new/
      - name: Prepare files
        id: prep
        run: |
          sudo chown -R runner:docker new
          sudo chmod 644 new/*
          cp edits.xml new/ || true
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Compare databases
        run: |
          cbng-trainer compare-database --target new/ --output new/ || true
      - name: Crease a release
        uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "new/*"
          bodyFile: "new/comparator.md"
          tag: "${{ steps.prep.outputs.date }}"
      - name: Update README
        run: |
          pip install requests
          ./.github/scripts/update-readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
